### ISSUE TITLE
Created jobs don't show up in ES

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-job-registry-elastic-api#28]
For some time we noticed that some jobs didn't end up in ES, and assumed it was a network/connection issue. 
I now found a minimal use case where I can consistently reproduce success/failure:

Consistently works: creating a job with progress graph
```json
{"add": {"process_id": "add", "arguments": {"x": 3, "y": 5}, "result": true}}
```
elastic job registry API responds with HTTP 201 and the job can be found in ES/Kibana

Consistently doesn't work: same process graph, but changing the "add" node name in some way ("add0", "addd", "add-foo", ...)
```json
{"add1": {"process_id": "add", "arguments": {"x": 3, "y": 5}, "result": true}}
```
elastic job registry API responds with HTTP 201 *but the job can be found in ES/Kibana*

**Comment by soxofaan** [comment]
Confirmed. All my test jobs now get through.
And `EJR API error: 404 \'Not Found\' on `PATCH ` errors now seem to have dropped to zero in the driver logs

**Comment by JanssenBrm** [comment]
A mapping explosion caused the issue. Because the `process` field was mapped as an `object`, ES also mapped all subfields. However, there is a limit on how many fields can be mapped (1000), causing an issue.

Even though an error occurred, the API still returned a 200 OK message. This is because the ES Bulk API was returning a 200 status but the response body contained a different status and error message. The code of the API was updated to also parse the body for any error message.
