### ISSUE TITLE
Multiple job support in POST /jobs

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-job-registry-elastic-api#3]
`POST /jobs` currently expects a list of jobs, so you can store multiple jobs at the same time.
I'm however not sure this is useful in practice where you will be mostly creating just one job at a time anyway.

Especially concerning error handling:
e.g. if you try to store N jobs and you get an error response: will it be easy to figure which subset of job worked an which subset failed?

side note: the swagger docs currently don't document the response body of the requests, so I'm not sure how much I can depend on the current responses I'm getting

**Comment by JanssenBrm** [comment]
I would suggest making it in line with the openeo driver code so that it matches its implementation. If the openeo code only reports one job at a time, it indeed does not make much sense (and would also mean more work) to accept an array of jobs. Changing it in the backend is also very easy.

If the array concept should be kept, we can send always send a reply where the body contains a status (OK, FAILED, ...) for each of the reported entries separately. Again, this would also induce more work as you won't receive an error status in those cases and need to parse the response.

Let me know what you would prefer and we'll change the API accordingly.

**Comment by JanssenBrm** [comment]
@soxofaan  - What do you think? Shall we update the API to only support single jobs?

**Comment by JanssenBrm** [comment]
Updated POST endpoint to support single jobs
